#!/bin/sh

logger "GTP-U ifup $@"

case $1 in
        gtp0)
                logger "Adjusting $1"
                # /sbin/ip link set dev $1 master upstream
                # /sbin/ip link set dev $1 mtu 1500
                # /sbin/ip route replace 10.180.0.0/16 dev $1 vrf upstream
                ;;
        *)
                ;;
esac

exit 0

